@startmindmap

* <b>Инструменты ТОС</b>
++ Критерии Проверки Логических Построений
+++_ Позволяют проверить, доказать или опровергнуть правильность выстроенных причинно-следственных связей.

+++ Критерии

++++ 1. Ясность
+++++_ Необходимы ли дополнительные устные разъяснения?
+++++_ Понятна ли важность высказывания?
+++++_ Являются ли контекст и слова двусмысленными?
+++++_ Разумна ли связь причины и следствия с точки зрения здравого смысла?
+++++_ Пропущены ли промежуточные логические звенья ("длинная стрелка")?

++++ 2. Наличие утверждения
+++++_ Законченное ли предложение?
+++++_ Имеет ли предложение смысл?
+++++_ Есть ли скрытое отношение "если-то"?
+++++_ Содержит ли только одну мысль (не является сложным)?
+++++_ Подтверждается ли на практике?

++++ 3. Наличие причинно-следственных отношений
+++++_ Выполняется ли отношение "если-то"?
+++++_ Звучит ли осмысленно при точном прочтении вслух?
+++++_ Причина очевидна? Если нет - искать другие проявления для проверки.

++++ 4. Достаточность приведенной причины
+++++_ Может ли причина самостоятельно привести к результату?
+++++_ Есть ли другие существенные факторы для данного явления?
+++++_ Достаточно ли только указанных причин для проявления результата в полном объеме?
+++++_ Причины вызывают следствие только в совокупности? ("И")
+++++_ Большинство явлений имеют несколько причин.
+++++_ "И" может быть строгим или усиливающим.
+++++_ Обычно основных причин не больше 4х, а влиянием остальных можно пренебречь.

++++ 5. Проверка наличия альтернативной причины
+++++_ Есть ли независимый фактор, который приводит к тому же результату?
+++++_ Если убрать исходную причину, исчезнет ли результат почти полностью? ("ИЛИ")
+++++_ Альтернатива может оказаться составной ("И") из малых причин.

++++ 6. Недопустимость подмены причины следствием
+++++_ Действительно ли причина вызывает такой результат, а не наоборот?
+++++_ Объясняет ли причина, почему существует следствие? Откуда мы узнаем, что оно существует?

++++ 7. Поиск проверочного следствия
+++++_ Является ли причина неявной?
+++++_ Если связи верны, то у причины еще может быть другое следствие.
+++++_ Выявленные следствия существуют только одновременно.
+++++_ Например, причина не может вызывать и прибыль, и убытки.

++++ 8. Отсутствие тавтологии
+++++_ Является ли причина явной?
+++++_ Нет зацикливания причины и следствия.


+++ Необходимость и достаточность
++++_ Чтобы произошло ЭТО, мы должны получить ТО-ТО, потому что ТО-ТО.
+++++_ ДРК, ДП.
++++_ Достаточно ли этих условий, чтобы явление наверняка имело место?
+++++_ ДТР, ДБР, ПП.
++++_ В основном КПЛП предназначены для принципа достаточности.


++ Дерево Текущей Реальности
+++_ Позволяет наглядно передать текущее состояние дел.
+++_ Отражает функциональную структуру организации, игнорируя организационную.

+++ Цель
++++_ Разобраться в сложных системах.
++++_ Обозначить <b>Нежелательные Явления</b> в системе.
++++_ Связать НЯ с <b>Истинными Причинами</b> через последовательность причин и следствий.
++++_ Если возможно, определить <b>Ключевую Проблему</b>, приводящую к появлению ~70% НЯ.
++++_ Понять, в каких случаях ИП или КП лежат вне зоны нашего влияния.
++++_ Выделить ряд ограничений, на которые следует направить усилия для скорейшего улучшения характеристик системы.
++++_ Принять решение о первом шаге, который позволит начать позитивные преобразования всей системы.

+++ Исходные условия
++++_ Причина-следствие и просто связанные факты - не одно и то же.
++++_ Элементы системы взаимосвязаны. Изменения в одних приведут к изменениям в других.
++++_ Все процессы системы и сама система в целом изменчивы (непрерывно меняются).
++++_ Воздействие на систему влечет за собой как желательные (предполагаемые) так и нежелательные (неожидаемые) явления.
++++_ НЯ в системе связаны друг с другом.
++++_ Желательные и НЯ в системе вызваны некими ИП, причем в большинстве случаев косвенно.
++++_ Формулировки причин и следствий необходимо анализировать, используя КПЛП.
++++_ За каждой установленной связью стоят определенные невысказанные предположения.
++++_ В данной системе при данных обстоятельствах одна и та же причина всегда ведет к одному определенному результату.

+++ Зоны
++++_ Зона контроля
+++++_ Почти абсолютная власть. Можем воздействовать на что угодно и как угодно.
++++_ Сфера влияния
+++++_ Можно в какой-то степени влиять на ход событий, но он не подчиняется нам полностью или напрямую.
++++_ Неконтролируемая область
+++++_ Приходится принять как данность.
+++++_ При достижении не останавливаться. Продолжать строить связи, насколько возможно.
+++++_ Но по готовности диаграммы проанализировать ситуацию. Возможно, сферу влияния можно расширить.

+++ Нежелательные явления
++++_ События, являющиеся негативными сами по себе.
++++_ Нежелательность - понятие субъективное.
+++++_ "А для кого я строю это дерево?"
++++_ Для других может оказаться желательным или безразличным.
+++++_ Симптом о наличии конфликта, который нужно разрешить.
+++++_ Или признак субоптимизации системы, когда один добивается высоких результатов за счет организации в целом.
++++_ Определить нежелательность
+++++_ Описать законченным предложением.
+++++_ Используются слова с ярко негативной окраской?
+++++_ Заинтересованные люди согласились, что явление само по себе негативно?
+++++_ Общество в целом признает явление негативным?
+++++_ Автору диаграммы явление представляется серьезным нарушением?
+++++_ Явление отрицательно сказывается на производительности всей системы (денежный или материальный поток)?
+++++_ "Ну и что в этом плохого?" от третьего лица. Найдется ли ответ "Из-за этого наступят (УЖАСНЫЕ ПОСЛЕДСТВИЯ)..."?
++++_ Убедиться в реальности существования НЯ
+++++_ Или это просто страхи?

+++ Истинная Причина
++++_ Последнее звено в сфере влияния.
++++_ Или первое звено в неконтролируемой области.
++++_ Может быть несколько ИП.
++++_ Необязательно негатив.
+++++_ "Солнце светит каждый день" и рак кожи.

+++ Ключевая Проблема
++++ Критерии
+++++_ ИП, ответственная за 70% НЯ и более.
+++++_ Соответствует вашему интуитивному представлению об источнике всех наблюдаемых трудностей.
+++++_ Действительно серьезная проблема, занимающая все ваши мысли.
+++++_ Ее решение полностью исключит вероятность повторения нежелательных событий.
++++_ Если решить КП не в наших силах, то сфокусироваться на ИП-х.
++++_ Среди всех ИП не найдена КП?
+++++_ Вероятно пропущены логические звенья цепи.
+++++_ Обычно пропущенное звено оказывается основанием сразу двух ветвей дерева (V-структура).
+++++_ Следует по очереди сопоставить каждую ИП с остальными
++++++_ Объединяет ли что-нибудь эти ИП?
++++++_ Может ли у них быть общий источник?
++++++_ Продолжать, пока не найдется пропущенная V-структура. Или до полного перебора ИП.
+++++_ Найти связи между утверждениями из разных ветвей.
++++++_ Возможно, через добавление промежуточных звеньев, чтобы связь стала очевидной.
+++++_ Если КП так и не найдена, то придется иметь дело с несколькими ИП.
+++++_ При поисках не выдавать желаемое за действительное и не придумывать то, чего не существует.
++++++_ Уж лучше несколько ИП.
++++++_ Главное удостовериться, что у каждого НЯ есть ИП.

++ Дерево Разрешения Конфликтов (Грозовая Туча)
+++_ f

++ Дерево Будущей Реальности
++ Дерево Переходов
++ План Преобразований

@endmindmap

